wandb_version: 1

competition:
  desc: null
  value: AG News Classification Dataset
_wandb_kernel:
  desc: null
  value: neuracort
_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.15.7
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1690776056.486956
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 3
      - 8
      - 16
      - 23
      4: 3.10.9
      5: 0.15.7
      8:
      - 4
      - 5
      10:
      - 9
